# Script to update the AWS Load Balancer Controller webhook CA bundle
# This should be run after the CA certificate has been generated by cert-manager

Write-Host "Waiting for CA certificate to be generated..."
kubectl wait --for=condition=ready certificate/aws-load-balancer-ca -n kube-system --timeout=300s

Write-Host "Extracting CA certificate..."
$CA_BUNDLE = kubectl get secret aws-load-balancer-ca-tls -n kube-system -o jsonpath='{.data.tls\.crt}'

Write-Host "Updating webhook configuration..."
kubectl patch validatingwebhookconfiguration aws-load-balancer-webhook `
  --type='json' `
  -p "[{'op': 'replace', 'path': '/webhooks/0/clientConfig/caBundle', 'value':'$CA_BUNDLE'}]"

Write-Host "Webhook CA bundle updated successfully!"